const experss = require('express')
const Speakeasy = require('speakeasy')
const BodyParser = require('body-parser')

var app = experss()

app.use(BodyParser.json())
app.use(BodyParser.urlencoded({extended : true}))


// ======================================================================================================
//Speakeasy this library gives you the for the time based authenntication process
//this end point gives the secret code whish should be converted into QR code and then been displayed
//based on this secret code the app will generate the 6 digit code which is used for validation 
//this secret should be stored into the datebase which will be used in the process of validation
//Refer Link https://www.youtube.com/watch?v=Yv5tZu5wAU0
// ======================================================================================================



app.get('/get-secret', (req, res, next) => {
    var secret = Speakeasy.generateSecret({ length : 20 }) //20 or any number here will be the secret key length which will be encode into "base32" format
    res.send({"secret" : secret.base32})
})

//This end point is for testing perpous. It gives us the 6 digit code that is used for validation  
//To make this code work should send "secret" in the bode through POSTMAN or AXIOS can use POST and GET Method
app.get('/get-input-code', (req, res, next) => {
    res.send({
        "token" : Speakeasy.totp({
            secret : req.body.secret,
            encoding : 'base32'
        }),
        "remaining" : (30 - Math.floor(new Date().getTime() / 1000.0 % 30)),
    })
})

//To make this code work should send "secret" and "token" in the bode through POSTMAN or AXIOS can use POST and GET Method
app.post('/validate', (req, res, next) => {
    res.send({
        'valid' : Speakeasy.totp.verify({
            secret : req.body.secret, // this secret key is the key generated by generateSecret() method should be stored in db
            encoding : 'base32',
            token : req.body.token,
            window : 0 // if window is set to 0 the 30 sec is the validation time.....if it is set to 1 then 60 sec is the validation time
        })
    })
})
app.listen(8081, () => {
    console.log("2 Factor Authenticator is Running")
})


